[package]
name = "operational"
version = "0.0.1"
authors = ["Sam Rijs <srijs@airpost.net>"]
description = "Operational Monad"
license = "MIT"
repository = "https://github.com/srijs/rust-operational"
keywords = ["free", "operational", "monad", "program", "interpreter"]
